FROM openjdk:21
WORKDIR /app
#compile  java application JAR file into the container
COPY ./target/restApi-0.0.1-SNAPSHOT.jar /app/restApi-0.0.1-SNAPSHOT.jar
# expose the port the spring application will run on 
EXPOSE 8080
ENTRYPOINT ["java","-jar","/app/restApi-0.0.1-SNAPSHOT.jar"]
