---
- name: Deploy Docker Compose App to EC2
  hosts: all
  become: true

  vars:
    aws_region: "eu-west-1" 
    ecr_registry: "668426476528.dkr.ecr.eu-west-1.amazonaws.com"  

  tasks:
    - name: Ensure app directory exists
      file:
        path: /opt/myapp
        state: directory
        mode: '0755'

    - name: Copy docker-compose.yml
      copy:
        src: docker-compose.yml
        dest: /opt/myapp/docker-compose.yml
        
    - name: Install AWS CLI
      ansible.builtin.package:
        name: awscli
        state: present

    - name: Log in to AWS ECR
      shell: |
        AWS_ACCESS_KEY_ID={{ aws_access_key_id }} \
        AWS_SECRET_ACCESS_KEY={{ aws_secret_access_key }} \
        aws ecr get-login-password --region eu-west-1 | \
        docker login --username AWS --password-stdin 668426476528.dkr.ecr.eu-west-1.amazonaws.com 
      environment:
        AWS_ACCESS_KEY_ID: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
        AWS_SECRET_ACCESS_KEY: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
       register: ecr_login

    - name: Show ECR login result (for debug)
      debug:
        var: ecr_login.stdout_lines

    - name: Run docker-compose up
      command: docker compose up -d
      args:
        chdir: /opt/myapp