- name: Deploy Docker Compose App to EC2
  hosts: ec2-instance
  become: true

  vars:
    aws_region: "eu-west-1"
    ecr_registry: "123456789012.dkr.ecr.eu-west-1.amazonaws.com"

  tasks:
    - name: Ensure app directory exists
      file:
        path: /opt/myapp
        state: directory
        mode: '0755'

    - name: Copy docker-compose.yml
      copy:
        src: "{{ playbook_dir }}/docker-compose.yml"
        dest: /opt/myapp/docker-compose.yml

    - name: Log in to AWS ECR
      become: true
      shell: |
        aws ecr get-login-password --region {{ aws_region }} | \
        docker login --username AWS --password-stdin {{ ecr_registry }}
      environment:
        AWS_ACCESS_KEY_ID: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
        AWS_SECRET_ACCESS_KEY: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
      register: ecr_login
      no_log: true  # Optional: hides sensitive output

    - name: Show ECR login result (for debug)
      debug:
        var: ecr_login.stdout_lines

    - name: Run docker-compose up
      become: true
      shell: docker compose up -d
      args:
        chdir: /opt/myapp
