name: Deploy Docker Compose to EC2

on:
  push:
    branches:
      - main  # or your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible sshpass

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}
          

     
          
      - name: Create playbook
        run: |
          cat > playbook.yml << 'EOF'
          ---
          - name: Deploy to EC2
            hosts: all
            become: yes
            
            tasks:
              - name: Update system packages
                yum:
                  name: '*'
                  state: latest
                when: ansible_os_family == "RedHat"
                
              - name: Install Docker
                shell: |
                  curl -fsSL https://get.docker.com -o get-docker.sh
                  sh get-docker.sh
                args:
                  creates: /usr/bin/docker
                  
              - name: Start Docker service
                systemd:
                  name: docker
                  state: started
                  enabled: yes
                  
              - name: Add ec2-user to docker group
                user:
                  name: ec2-user
                  groups: docker
                  append: yes
                  
              - name: Install Docker Compose
                shell: |
                  curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
                  chmod +x /usr/local/bin/docker-compose
                args:
                  creates: /usr/local/bin/docker-compose
                  
              - name: Test connection
                debug:
                  msg: "Successfully connected to {{ inventory_hostname }}"
          
		  EOF
      - name: Run Ansible playbook
        run: |
          ansible-playbook -i "${{ env.EC2_HOST }}," -u ec2-user --private-key ~/.ssh/id_rsa playbook.yml
          env:
            EC2_HOST: 3.249.160.176