name: Deploy to EC2 via Ansible

on:
  push:
    branches:
      - main  # or your target branch
  workflow_dispatch:  # Allow manual trigger

jobs:
  deploy:
    name: Ansible Deploy
    runs-on: ubuntu-latest

    env:
      EC2_HOST: ${{ secrets.EC2_HOST }}
      PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip
          pip install ansible boto3 botocore

      - name: Prepare SSH key
        run: |
          echo "$PRIVATE_KEY" > ansible/temp_key.pem 
          chmod 400 ansible/temp_key.pem

      - name: Run Ansible Playbook
        working-directory: ./ansible
        run: |
          ansible-playbook -i inventory.yaml deploy.yaml

      - name: Clean up SSH key
        if: always()
        run: rm -f ansible/temp_key.pem