name: Deploy Docker Compose to EC2

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible sshpass

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}
          
      - name: Run Ansible playbook
        env:
            EC2_HOST: 3.249.160.176
        run: |
          ansible-playbook -i "${{ env.EC2_HOST }}," -u ubuntu --private-key ~/.ssh/id_rsa ansible/ansible/playbook.yaml
          