name: Deploy Docker Compose to EC2

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest
    env: 
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      EC2_HOST: 3.253.74.102
      
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible sshpass

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}
          
      - name: Debug file list
        working-directory: ansible/ansible
        run: ls -l
        
      - name: Run Ansible playbook
        working-directory: ansible/ansible    
        run: |
          ansible-playbook -i "${{ env.EC2_HOST }}," \
            -u ubuntu \
            --ssh-extra-args="-o StrictHostKeyChecking=no" \
            playbook.yml
          