name: Ansible AWS Deploy

on:
  push:
    branches: [ "main" ]
    paths:
      - "ansible/"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python & Install Ansible
      run: |
        sudo apt update
        sudo apt install -y python3-pip
        pip3 install ansible boto boto3 botocore

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION || 'eu-west-1' }}

    - name: Run Ansible Playbook with AWS access
      run: |
        ansible-playbook ansible/deploy.yaml