name: Docker Build and Push

on:
  push:
    branches: [ "main", "master" ]
    paths:
      - 'src/**'
      - 'pom.xml'
      - 'build.gradle'
      - 'Dockerfile'
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Build the Spring Boot application
      - name: Build with Maven
        run: ./mvnw clean package

      # Step 4: Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Step 5: Build and push Docker image
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/restapi:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/restapi:${{ github.sha }}
          build-args: |
            SPRING_PROFILES_ACTIVE=prod
